In [1]:
import pandas as pd
import numpy as np


In [3]:
dataset = pd.read_csv('F:/Nividha/Lambton/CBD/Activity_2/mtcars.csv')
dataset.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [9]:
X = dataset.iloc[:, 1:4].values
y = dataset.iloc[:, 10].values
print(X)
print(y)

[[ 21.    6.  160. ]
 [ 21.    6.  160. ]
 [ 22.8   4.  108. ]
 [ 21.4   6.  258. ]
 [ 18.7   8.  360. ]
 [ 18.1   6.  225. ]
 [ 14.3   8.  360. ]
 [ 24.4   4.  146.7]
 [ 22.8   4.  140.8]
 [ 19.2   6.  167.6]
 [ 17.8   6.  167.6]
 [ 16.4   8.  275.8]
 [ 17.3   8.  275.8]
 [ 15.2   8.  275.8]
 [ 10.4   8.  472. ]
 [ 10.4   8.  460. ]
 [ 14.7   8.  440. ]
 [ 32.4   4.   78.7]
 [ 30.4   4.   75.7]
 [ 33.9   4.   71.1]
 [ 21.5   4.  120.1]
 [ 15.5   8.  318. ]
 [ 15.2   8.  304. ]
 [ 13.3   8.  350. ]
 [ 19.2   8.  400. ]
 [ 27.3   4.   79. ]
 [ 26.    4.  120.3]
 [ 30.4   4.   95.1]
 [ 15.8   8.  351. ]
 [ 19.7   6.  145. ]
 [ 15.    8.  301. ]
 [ 21.4   4.  121. ]]
[4 4 4 3 3 3 3 4 4 4 4 3 3 3 3 3 3 4 4 4 3 3 3 3 3 4 5 5 5 5 5 4]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [11]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 50)
classifier.fit(X_train, y_train)

RandomForestClassifier(n_estimators=50)

In [12]:
y_pred = classifier.predict(X_test)

In [13]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(result)
result1 = classification_report(y_test, y_pred)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(y_test,y_pred)
print("Accuracy:",result2)

Confusion Matrix:
[[3 0 1]
 [0 1 0]
 [1 1 0]]
Classification Report:
              precision    recall  f1-score   support

           3       0.75      0.75      0.75         4
           4       0.50      1.00      0.67         1
           5       0.00      0.00      0.00         2

    accuracy                           0.57         7
   macro avg       0.42      0.58      0.47         7
weighted avg       0.50      0.57      0.52         7

Accuracy: 0.5714285714285714
